### PR TITLE
Added loop func

### PR DESCRIPTION
**Pull request by Sadman26**
I have made a loop function that is `void` type function and basically it takes a parameter which is the length of the code thats all ✌

### CODE REVIEW

**Review by Sadman-123 — CHANGES_REQUESTED** [review]
Thats ok ! But You haven't call the function DO IT!!

**Comment by Sadman26** [comment]
Okk

**Comment by Sadman26** [comment]
ok

**Review by Sadman-123 — APPROVED** [review]
Thats Fine!! Be more sincere dude 🤔

**Pull request merged**
